const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.svg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 20,
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.svg',
      price: 100,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 10,
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.svg',
      price: 220,
      brand: 'Lacoste',
      rating: 3.8,
      numReviews: 17,
      description: 'high quality product',
      countInStock: 0,
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.svg',
      price: 78,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 14,
      description: 'high quality product',
      countInStock: 16,
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.svg',
      price: 65,
      brand: 'Puma',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 1,
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.svg',
      price: 139,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
      countInStock: 100,
    },
  ],
};
export default data;